export enum AuditoriaAcaoEnum {
  SANGRIA = "SANGRIA",
  SUPRIMENTO = "SUPRIMENTO",
  CANCELAMENTO = "CANCELAMENTO",
  ESTORNO = "ESTORNO",
  ABERTURA = "ABERTURA",
  FECHAMENTO = "FECHAMENTO",
  LIBERACAO = "LIBERACAO",
}
