export const PEDIDO_STATUS = {
  PENDENTE: "PENDENTE",
  AGUARDANDO_PAGAMENTO: "AGUARDANDO_PAGAMENTO",
  PAGO: "PAGO",
  EM_SEPARACAO: "EM_SEPARACAO",
  EM_PREPARACAO: "EM_PREPARACAO",
  SEPARADO: "SEPARADO",
  SAIU_PARA_ENTREGA: "SAIU_PARA_ENTREGA",
  ENTREGUE: "ENTREGUE",
  FINALIZADO: "FINALIZADO",
  CANCELADO: "CANCELADO",
  DEVOLVIDO: "DEVOLVIDO",
} as const;